# Generated by Django 2.2 on 2021-03-22 16:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='avatar',
            field=models.CharField(max_length=300, null=True, verbose_name='Avatar seleccionado'),
        ),
        migrations.AddField(
            model_name='user',
            name='id_course_scorm',
            field=models.CharField(max_length=100, null=True, verbose_name='ID del curso en SCORM'),
        ),
        migrations.AddField(
            model_name='user',
            name='id_level_scorm',
            field=models.CharField(max_length=100, null=True, verbose_name='ID del nivel en SCORM'),
        ),
        migrations.AddField(
            model_name='user',
            name='username_scorm',
            field=models.CharField(max_length=100, null=True, verbose_name='ID en SCORM'),
        ),
    ]
