# Generated by Django 2.2 on 2021-03-24 15:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_user_id_user_scorm'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='area',
            field=models.CharField(blank=True, max_length=300, null=True, verbose_name='área'),
        ),
        migrations.AddField(
            model_name='user',
            name='puesto',
            field=models.CharField(blank=True, max_length=300, null=True, verbose_name='Avatar seleccionado'),
        ),
    ]
